### ISSUE TITLE
How to install...?

### ISSUE THREAD

**Issue by sardaukar** [dmcoles/AmiExpress#44]
I'm eager to try this BBS software. I have a MiST FPGA Amiga 1200 emulator, which is already online with Genesis 1.0.4. Is it possible to have some documentation on how to install and set this up? Maybe with telser or telnetd?

**Comment by dmcoles** [comment]
so you could start with something like this as an absolutely blank canvas. it has 2 nodes, node 0 is for your own local login and node 1 is set up for telnetd.device

[bbs.zip](https://github.com/dmcoles/AmiExpress/files/3276518/bbs.zip)

put the folders from this zip in the relevant places and assign BBS: to your bbs folder and DOORS: to the doors subfolder. Edit the tooltypes in acp.info to specify your bbs name, sysop name and anything else you want to change. 

That should get you started with a bare minimum. There will be lots of screens you will want to set up and doors you want to add after that though.

If you want more advice then the Ami-Express Sysops group on facebook has lots of users who can advise (including myself).

**Comment by sardaukar** [comment]
Thanks for this - I'm not on Facebook, though :| 

My problem seems to be setting up the TCP/IP stack, specifically telnetd or telser (I have both).

What do I need to put in `db/passwd` or `db/telserd.conf` for Telnet connections to be passed on to `fakesr.device` or `serial.device` ?

**Comment by dmcoles** [comment]
i'd go with telnetd.device all you need to do then is configure each node by putting telnetd.device and the unit number into the serial configuration in /X and TELNETD into each node.info then all you need do is put telnetd.device in devs: and telnetd-device.conf in your db/ folder containing something like this

23 3 255.255.255.255

that is port, number of nodes and network mask.

/X and telnetd take care of everything else - no need to mess with anything in your tcp stack.

**Comment by sardaukar** [comment]
Do you know where I can get telnetd.device? I can only find fakesr.device in telnetd-2.0, and telser.device in TelSer 1.4 in Aminet.

**Comment by dmcoles** [comment]
> 
> 
> Do you know where I can get telnetd.device? I can only find fakesr.device in telnetd-2.0, and telser.device in TelSer 1.4 in Aminet.

http://aminet.net/package/comm/net/tnddev1p0.lha

**Comment by sardaukar** [comment]
I got `error parsing db/telnetd-device.conf: Argument error or line too long` with `23 2 255.255.255.255`. This shouldn't be happening, right? Also, a lot of the files in your `.zip` look like projects, and make the screen blink when I try to open them (like `acp`). I think the zip file was created outside of Workbench so it doesn't have all the file .infos needed. 

Anyway - thanks for your help, but I guess I'm done trying to make this work.

**Comment by sardaukar** [comment]
I think my version of `telnetd.device` was borked, I got it to work with the aminet version. But it's only the shareware version, so it doesn't let me login from outside my local network and I can't find the full version anywhere online :|

**Comment by sardaukar** [comment]
I managed to get online and blog about it https://blog.nootch.net/post/amiga-bbs-online-2019/ I'm eager to try Amiexpress next!

**Comment by sardaukar** [comment]
@dmcoles since I managed to make it work via serial, how should I configure /X ?

**Comment by dmcoles** [comment]
sorry i'm not sure what you are asking... is it something particular you are asking about configuring or the whole lot? If the whole lot then i'd suggest using the sysop in a minute package from amiexpress.co.uk and replacing the ACP and Express files with the 5.1.0 ones from here.

**Comment by ata-star** [comment]
Hello, i am interested in writing a Tutorial for this and supporting this project @dmcoles but first i need to see it working...

**Comment by dmcoles** [comment]
I'm happy to help you get it set up - we can discuss over facebook messenger, mewe, discord, signal, whatsapp or email

**Comment by ata-star** [comment]
Facebook messenger : https://www.facebook.com/lukas.friedrich.5895/
Discord : dracc#1337
you decide

**Comment by flewid** [comment]
hello, i would also be interested in a bit of a tutorial, how do i contact you on signal @dmcoles  ?
