### ISSUE TITLE
How to you install Rpstart since the author forgot to include the details in his release

### ISSUE THREAD

**Issue by ptaylor2** [dmcoles/AmiExpress#46]
How to you install Rpstart since the author forgot to include the details in his release

**Comment by dmcoles** [comment]
It is covered here in the documentation https://github.com/dmcoles/AmiExpress/wiki/Host-Addresses

**Comment by dmcoles** [comment]
i'm not even sure this is needed to be honest. it was in the original /X documentation but I don't have anything called RPStart in my user-startup. Just RexxMast
