### ISSUE TITLE
Documentation Requirements not clear

### ISSUE THREAD

**Issue by swissAlisha** [dmcoles/AmiExpress#57]
Hi,

I try to install AmiExpress, but it's not clear witch paket you are requesting for followoing Requirements

First One is clear AmiSSL, but Remote Shell and Optional serial locking, can you please link it to the right packet on aminet.net or add the packet to search to have the right packet to be install.

[Quote from the Documentation]
In addition to the above machine requirements there are some features which have additional requirements

Feature | Requirement
-- | --
Email notifications | AmiSSL.library is required to interface to an SMTP server in order to send email notifications
Remote Shell | fifo-handler and fifo.library is required to pipe the input and ouput to the shell handler
Optional serial locking | owndevunit.library is required to facilitate the locking process

[/Quote from the Documentation]
Best regards
Alisha

**Comment by dmcoles** [comment]
These are the two packages...
http://aminet.net/package/comm/misc/OwnDevUnit
http://aminet.net/package/dev/gg/fifolib-bin

Neither are required to get ami-express up and running though. Feel free to contact me if you need assistance in getting it installed and set up..

https://twitter.com/AmiExpressBBS
https://www.facebook.com/AmiExpressBBS
https://discord.gg/FDVUBGZThq
