### ISSUE TITLE
Express has crash on local node exit/Goodbye (ACA500+ only?)

### ISSUE THREAD

**Issue by IBBBS** [dmcoles/AmiExpress#62]
Configuration:
A500 with IComp's ACA500+
Motherboard: REV 6A
Flashed Kickstart 3.2.2 to ACA
Workbench 3.2.2.1

ACA Configurations: All options I could think of were tested Including:
- Numerous varying memory configurations
- Turning off ACA500 features such as ACAResource, IDE driver 
- Using  Kickstart 3.1 instead
- Attempted both 7HZ and 14HZ CPU options
   Note: 7HZ not optimal for BBS use on the A500, so really is no-starter, but was attempted anyway.

**Actions to recreate:**
- Sysop Login or normal login invoked on Local Node
- Normal functions through to conference
- Logout (Goodbye)

**Result:** 
- System does a flash on the screen and able to see for a moment "AutoSaving File Flags" (line 2803 of express.e)
- Power light flash
- Guru: Error: 8000 0003 TASK: <various results>

**Additional observations:**
- This could not be replicated in WIN-UAE with "as close" to a profile as I could figure out to replicate ACA500+
- Could not be replicated with same A500 running with EMU68K (no ACA500+) - BBS functions normally
- If this is supposed to create an audible "Ding!" to the user, no "Ding!" occurred ;-) - But I don't hear it in the non-crashing EMU68K environment either.

Best guess off limited brain cell capacity: consoleIO invoking "BELL" from PROC saveBELL() ??
- **Proc sendBELL()** at line 5231
- invokes **aePuts()** with "BELL"-> **aePuts2()** -> assume this invokes **conPuts()** -> **consoleIO** -> send command at line 1868 with **doIO**

May see if I can trip system up with File Flag listing where this same procedure also occurs (line 2793 of express.e)

**Node 0 configuration:**
NODESTART=bbs:Express
PRIORITY=-1
CAPITOL_FILES
KEEP_UPLOAD_CREDIT=1
NO_TIMEOUT
NO_WILDCARD_EXPANSION
RINGCOUNT=1
DEF_SCREENS

**Comment by IBBBS** [comment]
I may have to backtrack on my limited brain cell synopsis / analysis ;-)
Per my observations mentioned above:

"System does a flash on the screen and able to see for a moment "AutoSaving File Flags"   "

This is seen everytime before the crash. In the EMU68K environment, I just noticed I'm not getting that text at all. So I'm not getting to sendBELL()...

**Comment by IBBBS** [comment]
The implemented fix version sent to me corrected the issue. recommend implementation.

**Comment by dmcoles** [comment]
i have created a v5.6.1 branch with the changes in. these will be released in the near future

**Comment by dmcoles** [comment]
issues with 68000 crashes are fixed in 5.6.1
